### PR TITLE
Check links in documentation as part of build

### PR DESCRIPTION
**Pull request by erikbosch**
This automates the check link step in https://github.com/eclipse-kuksa/kuksa-databroker/wiki/Release-Process. It will check links on every pull request. Previously we just tested it manually before doing a release.

If this is merged we should update the wiki.

### CODE REVIEW

**Comment by erikbosch** [comment]
Add temporarily a commit with a failing link

image

The underlying framework currently only "understands" mark-down files and just takes links, so not for examples in code snippets.
Checking other file types could be more difficult - how do we know if a URL is supposed to work in a public environment.

**Comment by wba2hi** [comment]
When I ran through the release steps I also find this command here: 
`find . -name \*.md -print0 | xargs -0 -n1 markdown-link-check` and it found a lot more: 

```
FILE: ./README.md
  27 links checked.

  ERROR: 6 dead links found!
  [✖] https://github.com/github_username/repo_name → Status: 404
  [✖] https://github.com/eclipse-kuksa/kuksa-databrokerissues → Status: 404
  [✖] #built-with → Status: 404
  [✖] #installation → Status: 404
  [✖] #roadmap → Status: 404
  [✖] #readme-top → Status: 404
(node:40710) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

FILE: ./doc/user_guide.md
  22 links checked.

  ERROR: 3 dead links found!
  [✖] #enabling-tLS → Status: 404
  [✖] #top → Status: 404
  [✖] http://127.0.0.1:55555 → Status: 0
(node:40714) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

FILE: ./doc/authorization.md
  44 links checked.

  ERROR: 1 dead links found!
  [✖] #jwt-access-token → Status: 404
(node:40722) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

FILE: ./doc/system-architecture.md
  ERROR: 2 dead links found!
  [✖] https://github.com/eclipse/kuksa.val.feeders/tree/main/dbc2val → Status: 404
  [✖] https://github.com/eclipse/kuksa.val.feeders/tree/main/someip2val → Status: 404
(node:40724) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

FILE: ./doc/terminology.md
  27 links checked.

  ERROR: 2 dead links found!
  [✖] #vehicle-signal-specification-vss → Status: 404
  [✖] https://covesa.github.io/vehicle_signal_specification/rule_set/data_entry/data_unit_types/ → Status: 404
(node:40734) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)


FILE: ./doc/QUERY.md
  16 links checked.

  ERROR: 4 dead links found!
  [✖] #121-time--conceptual-row-view → Status: 404
  [✖] #13-subscribing-to-multiple-data-points--signals → Status: 404
  [✖] #211-time--conceptual-row-view → Status: 404
  [✖] #221-time--conceptual-row-view → Status: 404
(node:40738) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

FILE: ./doc/deployment.md
  17 links checked.

  ERROR: 1 dead links found!
  [✖] #mixing → Status: 404
(node:40740) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

FILE: ./data/vss-core/README.md
  16 links checked.

  ERROR: 5 dead links found!
  [✖] https://github.com/eclipse/kuksa.val.feeders/blob/main/dbc2val/mapping/mapping.md → Status: 404
  [✖] https://github.com/eclipse/kuksa.val.feeders/blob/main/dds2val/ddsproviderlib/idls/generate_py_dataclass.sh → Status: 404
  [✖] https://github.com/eclipse/kuksa.val.feeders/blob/main/dbc2val/Readme.md → Status: 404
  [✖] httpts://github.com/eclipse/kuksa.val.feeders/blob/main/dbc2val/candump.log → Status: 404
  [✖] https://github.com/eclipse/kuksa.val.feeders/blob/main/dbc2val/mapping → Status: 404
```

Not all of them are useful, as some of them are just anchors which have no anchor point. I tried fixing the "sane" errors, find the patch attached: 
[kuksa-databroker-11-38-36.patch](https://github.com/user-attachments/files/15584692/kuksa-databroker-11-38-36.patch)

Maybe it helps you, but I would still expect the task to run with a few of those?

**Comment by erikbosch** [comment]
I do not really remember why we (i.e. I) excluded 404 errors once upon a time. Will check it out

**Comment by wba2hi** [comment]
> Result of analysis:
> [...]
>     * I suggest for now - until markdown-link-check is stable - that we accept 404 errors to not fail CI, but state that a manual check of 404 should happen as part of release

Sounds reasonable to me, let's do it this way, having any check is better than none at all

**Comment by erikbosch** [comment]
I think this one is good to go now. I created an issue at https://github.com/eclipse-kuksa/kuksa-actions/issues/10 to follow up on how we could include 404 errors as well

**Review by wba2hi — APPROVED** [review]
LGTM

**Comment by SebastianSchildt** [comment]
Seems useful, but needs rebase @wba2hi

**Comment by erikbosch** [comment]
@SebastianSchildt - I did a rebase. There were actually no conflicts, not even the same files are changed. To me it seems that the defautl setup has changed so that it propose rebase always, which in one way is good.

**Pull request merged**
